name: floca
description: Flutter localization library
repository: https://github.com/rtmigo/floca
version: 0.1.0-alpha.1


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  csv: ^5.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: any
